version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "bad-rabbit"
  redis:
    hostname: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    build: .